name: Build

on:
  push:
    branches:
      - main


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Deploy the new api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/html/api
            rm -r *
            wget https://github.com/ZeGamerc/HwpAPI/archive/refs/heads/main.zip
            unzip main.zip